const express = require("express");
const router = express.Router();
const checkauth = require("../../utils/middlewares/auth1");
// const { orders } = require("../../controllers/order");
const { book , findOrder, cancelorder  } = require("../../controllers/order");
const { DETAILS, HISTORY , BOOK , CANCEL } = require("../../utils/config").ROUTES.ORDER;
router.post(BOOK, book);
router.get(DETAILS,  checkauth ,findOrder);
router.post(CANCEL , cancelorder);
// router.get(DETAILS + "/:orderid", orders);
module.exports = router;
